### ISSUE TITLE
Generate config files in volume

### ISSUE THREAD

**Issue by eonpatapon** [nlewo/nixpkgs-cloudwatt#36]
In contrail images we have:

```
consul-template-wrapper -- -once \
        -template="${config.contrail.api}:/etc/contrail/contrail-api.conf"
```

We have to generate theses config files in a volume (usually `/run/consul-template-wrapper`).

In the case the pod restart we can't generate the file again because the vault token is only usuable once. If the conf file is generated in a volume `consul-template-wrapper` will not try to regenerate it again.

**Comment by k-ayache** [comment]
The path of vnc_lib_api file is specified in source code of contrail at /etc/contrail/, we can't change it, we have to play with the token to be generated each time the pod is down or something else
